# -*- coding: utf-8 -*-
"""Healthark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1as1-4Xbtf-XkcfsVP6tmNdWy4BtoiOZy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

folder_path="/content/drive/MyDrive/Healthark"

"""#Beneficiary Dataset"""

Benefi_08=pd.read_csv(folder_path+"/DE1_0_2008_Beneficiary_Summary_File_Sample_1.csv")
Benefi_09=pd.read_csv(folder_path+"/DE1_0_2009_Beneficiary_Summary_File_Sample_1.csv")
Benefi_10=pd.read_csv(folder_path+"/DE1_0_2010_Beneficiary_Summary_File_Sample_1.csv")

print(Benefi_08.shape)
print(Benefi_09.shape)
print(Benefi_10.shape)

print(Benefi_08.columns)
print(Benefi_09.columns)
print(Benefi_10.columns)

print(Benefi_08.describe)

print(Benefi_08.isnull().sum())
print(Benefi_09.isnull().sum())
print(Benefi_10.isnull().sum())

all_years_df = pd.concat([Benefi_08, Benefi_09, Benefi_10], ignore_index=True)
print(all_years_df.shape)
display(all_years_df.head())

all_years_df.to_csv(folder_path + "/all_beneficiary_data.csv", index=False)

"""#Impatient & Outpatient dataset"""

inpatient_claims = pd.read_csv(folder_path+"/DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv")
outpatient_claims = pd.read_csv(folder_path+"/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv")

# Load and concatenate Inpatient and Outpatient Claims Data
inpatient_claims = pd.read_csv(folder_path+"/DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv")
outpatient_claims = pd.read_csv(folder_path+"/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv", low_memory=False)

# Concatenate the dataframes
all_claims_df = pd.concat([inpatient_claims, outpatient_claims], ignore_index=True)

print("Shape of concatenated claims data:", all_claims_df.shape)
display(all_claims_df.head())

# Analyze missing values in the concatenated claims data
missing_values = all_claims_df.isnull().sum()
missing_percentage = (missing_values / len(all_claims_df)) * 100

missing_info = pd.DataFrame({'Missing Values': missing_values, 'Missing Percentage (%)': missing_percentage})
missing_info = missing_info[missing_info['Missing Values'] > 0].sort_values(by='Missing Values', ascending=False)

print("Missing values in the concatenated claims data:")
display(missing_info)

# Convert date columns to datetime objects
all_claims_df['CLM_FROM_DT'] = pd.to_datetime(all_claims_df['CLM_FROM_DT'], format='%Y%m%d', errors='coerce')
all_claims_df['CLM_THRU_DT'] = pd.to_datetime(all_claims_df['CLM_THRU_DT'], format='%Y%m%d', errors='coerce')

# Calculate length of stay for inpatient claims
# Assuming inpatient claims have a different SEGMENT value or can be identified otherwise.
# Based on the data description (not provided here), let's assume segment 1 is for inpatient.
# We should verify this assumption based on the actual data dictionary if available.
all_claims_df['length_of_stay'] = (all_claims_df['CLM_THRU_DT'] - all_claims_df['CLM_FROM_DT']).dt.days

# Display the updated DataFrame with new features
display(all_claims_df[['CLM_FROM_DT', 'CLM_THRU_DT', 'length_of_stay']].head())

# Extract the year from the claim start date
all_claims_df['claim_year'] = all_claims_df['CLM_FROM_DT'].dt.year

# Calculate the number of claims per year
claims_per_year = all_claims_df['claim_year'].value_counts().sort_index()

print("Number of claims per year:")
display(claims_per_year)

# Calculate total medical reimbursement and beneficiary deductible amounts per year
financial_summary_per_year = all_claims_df.groupby('claim_year')[['NCH_PRMRY_PYR_CLM_PD_AMT', 'NCH_BENE_PTB_DDCTBL_AMT']].sum()

print("\nFinancial summary per year (Total Reimbursement and Deductible):")
display(financial_summary_per_year)

# Analyze the most common diagnoses (ICD9_DGNS_CD_1 to ICD9_DGNS_CD_10)
diagnosis_columns = [f'ICD9_DGNS_CD_{i}' for i in range(1, 11)]
all_diagnoses = all_claims_df[diagnosis_columns].stack().reset_index(drop=True)
top_diagnoses = all_diagnoses.value_counts().head(10)

print("Top 10 Most Common Diagnoses:")
display(top_diagnoses)

# Analyze the most common procedures (ICD9_PRCDR_CD_1 to ICD9_PRCDR_CD_6)
procedure_columns = [f'ICD9_PRCDR_CD_{i}' for i in range(1, 7)]
all_procedures = all_claims_df[procedure_columns].stack().reset_index(drop=True)
top_procedures = all_procedures.value_counts().head(10)

print("\nTop 10 Most Common Procedures:")
display(top_procedures)

# Analyze claims data by provider (PRVDR_NUM)
# Count the number of claims per provider
claims_per_provider = all_claims_df['PRVDR_NUM'].value_counts().head(10)

print("Top 10 Providers by Number of Claims:")
display(claims_per_provider)

# Calculate the total medical reimbursement amount per provider
reimbursement_per_provider = all_claims_df.groupby('PRVDR_NUM')['NCH_PRMRY_PYR_CLM_PD_AMT'].sum().sort_values(ascending=False).head(10)

print("\nTop 10 Providers by Total Medical Reimbursement:")
display(reimbursement_per_provider)

# Merge claims data with the beneficiary data
# Assuming the common column is 'DESYNPUF_ID'
merged_df = pd.merge(all_claims_df, all_years_df, on='DESYNPUF_ID', how='left')

print("Shape of merged data:", merged_df.shape)
display(merged_df.head())

# Analyze claims related to specific chronic conditions
# Assuming the chronic condition columns are prefixed with 'SP_'
chronic_condition_cols = [col for col in merged_df.columns if col.startswith('SP_')]

for condition in chronic_condition_cols:
    # Filter data for beneficiaries with the chronic condition (assuming '1' indicates presence)
    condition_df = merged_df[merged_df[condition] == 1]

    if not condition_df.empty:
        print(f"\nAnalysis for beneficiaries with {condition}:")
        # Example analysis: average medical reimbursement for this group
        avg_reimbursement = condition_df['NCH_PRMRY_PYR_CLM_PD_AMT'].mean()
        print(f"Average Medical Reimbursement: ${avg_reimbursement:,.2f}")

        # Example analysis: most common diagnoses for this group
        diagnosis_columns = [f'ICD9_DGNS_CD_{i}' for i in range(1, 11)]
        condition_diagnoses = condition_df[diagnosis_columns].stack().reset_index(drop=True)
        top_condition_diagnoses = condition_diagnoses.value_counts().head(5)
        print("Top 5 Most Common Diagnoses for this group:")
        display(top_condition_diagnoses)
    else:
        print(f"\nNo data available for beneficiaries with {condition}.")


# Analyze claims data based on state and county codes
# Example analysis: Total medical reimbursement per state
reimbursement_per_state = merged_df.groupby('SP_STATE_CODE')['NCH_PRMRY_PYR_CLM_PD_AMT'].sum().sort_values(ascending=False).head(10)

print("\nTop 10 States by Total Medical Reimbursement:")
display(reimbursement_per_state)

# Example analysis: Number of claims per county (for a specific state, or top counties overall)
# Let's look at the top 10 counties by claim count
claims_per_county = merged_df['BENE_COUNTY_CD'].value_counts().head(10)

print("\nTop 10 Counties by Number of Claims:")
display(claims_per_county)

# Feature Creation for Modeling

# Aggregate features at the beneficiary level from claims data
beneficiary_claims_summary = merged_df.groupby('DESYNPUF_ID').agg(
    total_claim_count=('CLM_ID', 'count'),
    total_reimbursement=('NCH_PRMRY_PYR_CLM_PD_AMT', 'sum'),
    total_beneficiary_deductible=('NCH_BENE_PTB_DDCTBL_AMT', 'sum'),
    average_length_of_stay=('length_of_stay', 'mean')
).reset_index()

print("\nBeneficiary-level claims summary for modeling:")
display(beneficiary_claims_summary.head())

# You can further merge this summary back to the beneficiary data if needed
# final_modeling_df = pd.merge(all_years_df, beneficiary_claims_summary, on='DESYNPUF_ID', how='left')
# display(final_modeling_df.head())

"""#Other datasets"""

drug=pd.read_excel(folder_path+"/drug_exposure.xlsx")

drug.columns

drug.info()

concept=pd.read_csv(folder_path+"/concept - CONCEPT.csv")

concept.columns

condition=pd.read_excel(folder_path+"/condition_occurrence.xlsx")

condition.columns

person=pd.read_excel(folder_path+"/person.xlsx")

person.columns

"""# Task
PREDICTION TASK: Will the patient be readmitted within 30/60/90 days using data from "beneficiary_data.csv" and "inpatient_claims_data.csv".

## Identify readmissions

### Subtask:
Define readmission within 30, 60, and 90 days using the claims data and beneficiary death dates.

**Reasoning**:
Sort the claims data, calculate the time difference between consecutive claims for each beneficiary, define the readmission flags based on 30, 60, and 90-day thresholds, handle claims after death dates, and shift the readmission flags to predict readmission after a claim.
"""

# Load and concatenate Inpatient and Outpatient Claims Data
inpatient_claims = pd.read_csv(folder_path+"/DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv")
outpatient_claims = pd.read_csv(folder_path+"/DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv", low_memory=False)

# Concatenate the dataframes
all_claims_df = pd.concat([inpatient_claims, outpatient_claims], ignore_index=True)

# Convert date columns to datetime objects
all_claims_df['CLM_FROM_DT'] = pd.to_datetime(all_claims_df['CLM_FROM_DT'], format='%Y%m%d', errors='coerce')
all_claims_df['CLM_THRU_DT'] = pd.to_datetime(all_claims_df['CLM_THRU_DT'], format='%Y%m%d', errors='coerce')

# Calculate length of stay for inpatient claims
all_claims_df['length_of_stay'] = (all_claims_df['CLM_THRU_DT'] - all_claims_df['CLM_FROM_DT']).dt.days


# Step 1: Sort the all_claims_df DataFrame
all_claims_df = all_claims_df.sort_values(by=['DESYNPUF_ID', 'CLM_FROM_DT'])

# Step 2: Calculate the time difference between consecutive claim start dates
all_claims_df['days_between_claims'] = all_claims_df.groupby('DESYNPUF_ID')['CLM_FROM_DT'].diff().dt.days

# Step 3 and 4: Create readmission flags
all_claims_df['readmit_30'] = (all_claims_df['days_between_claims'] <= 30).astype(int)
all_claims_df['readmit_60'] = (all_claims_df['days_between_claims'] <= 60).astype(int)
all_claims_df['readmit_90'] = (all_claims_df['days_between_claims'] <= 90).astype(int)

# Step 5: Handle claims after death dates
# Recreate all_years_df by concatenating the beneficiary dataframes
all_years_df = pd.concat([Benefi_08, Benefi_09, Benefi_10], ignore_index=True)
# Convert BENE_DEATH_DT to datetime
all_years_df['BENE_DEATH_DT'] = pd.to_datetime(all_years_df['BENE_DEATH_DT'], format='%d-%m-%Y', errors='coerce')

# Merge death dates into the claims data
all_claims_df = pd.merge(all_claims_df, all_years_df[['DESYNPUF_ID', 'BENE_DEATH_DT']], on='DESYNPUF_ID', how='left')

# Identify claims that occurred after the beneficiary's death date
claims_after_death = all_claims_df['CLM_FROM_DT'] > all_claims_df['BENE_DEATH_DT']

# Set readmission flags to 0 for claims after death
all_claims_df.loc[claims_after_death, ['readmit_30', 'readmit_60', 'readmit_90']] = 0

# Step 6: Shift the readmission flags to the previous row
all_claims_df['readmit_30_next'] = all_claims_df.groupby('DESYNPUF_ID')['readmit_30'].shift(-1).fillna(0).astype(int)
all_claims_df['readmit_60_next'] = all_claims_df.groupby('DESYNPUF_ID')['readmit_60'].shift(-1).fillna(0).astype(int)
all_claims_df['readmit_90_next'] = all_claims_df.groupby('DESYNPUF_ID')['readmit_90'].shift(-1).fillna(0).astype(int)

# Drop the original readmission flags as they refer to the time *before* the current claim and the death date column
all_claims_df = all_claims_df.drop(columns=['readmit_30', 'readmit_60', 'readmit_90', 'BENE_DEATH_DT'])

# Rename the shifted columns
all_claims_df = all_claims_df.rename(columns={
    'readmit_30_next': 'readmit_30',
    'readmit_60_next': 'readmit_60',
    'readmit_90_next': 'readmit_90'
})


# Display the updated DataFrame with new readmission flags
display(all_claims_df[['DESYNPUF_ID', 'CLM_FROM_DT', 'days_between_claims', 'readmit_30', 'readmit_60', 'readmit_90']].head())

"""## Feature engineering

### Subtask:
Create features from the claims and beneficiary data that could be predictive of readmission, such as number of claims, total reimbursement, length of stay, chronic conditions, demographics, and drug exposures.

**Reasoning**:
The previous step identified readmissions. Now I need to create features for modeling by merging claims and beneficiary data and aggregating information at the beneficiary level. I will also incorporate data from the drug and condition tables.
"""

# Merge claims data with the beneficiary data
# Assuming the common column is 'DESYNPUF_ID'
merged_data = pd.merge(all_claims_df, all_years_df, on='DESYNPUF_ID', how='left')

# Aggregate features at the beneficiary level from claims data
beneficiary_claims_summary = merged_data.groupby('DESYNPUF_ID').agg(
    total_claim_count=('CLM_ID', 'count'),
    total_reimbursement=('NCH_PRMRY_PYR_CLM_PD_AMT', 'sum'),
    total_beneficiary_deductible=('NCH_BENE_PTB_DDCTBL_AMT', 'sum'),
    average_length_of_stay=('length_of_stay', 'mean'),
    # Include readmission flags aggregated at the beneficiary level (e.g., max to see if they had at least one readmission)
    had_readmit_30=('readmit_30', 'max'),
    had_readmit_60=('readmit_60', 'max'),
    had_readmit_90=('readmit_90', 'max')
).reset_index()

# Merge the beneficiary_features DataFrame with the all_years_df DataFrame
final_features_df = pd.merge(all_years_df, beneficiary_claims_summary, on='DESYNPUF_ID', how='left')

# Incorporate features from drug and condition data
# Assuming 'PERSON_ID' in drug and condition tables corresponds to 'DESYNPUF_ID'
# Aggregate drug exposure data at the person level
drug_summary = drug.groupby('PERSON_ID').agg(
    total_drug_exposures=('DRUG_EXPOSURE_ID', 'count'),
    total_days_supply=('DAYS_SUPPLY', 'sum')
).reset_index()

# Aggregate condition occurrence data at the person level
condition_summary = condition.groupby('PERSON_ID').agg(
    total_condition_occurrences=('CONDITION_OCCURRENCE_ID', 'count')
).reset_index()

# Merge drug and condition summaries into the final features DataFrame
final_features_df = pd.merge(final_features_df, drug_summary, left_on='DESYNPUF_ID', right_on='PERSON_ID', how='left')
final_features_df = pd.merge(final_features_df, condition_summary, left_on='DESYNPUF_ID', right_on='PERSON_ID', how='left')

# Drop the duplicate 'PERSON_ID' columns
final_features_df = final_features_df.drop(columns=['PERSON_ID_x', 'PERSON_ID_y'], errors='ignore')


# Inspect the resulting final_features_df
print("Shape of final features data:", final_features_df.shape)
display(final_features_df.head())
display(final_features_df.columns)

"""## Data preparation for modeling

### Subtask:
Prepare the data for machine learning by handling missing values, encoding categorical variables, and splitting the data into training and testing sets.

**Reasoning**:
Identify columns with missing values and apply imputation. Then, identify categorical columns and apply one-hot encoding. Finally, define target variables and split the data into training and testing sets.
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# 1. Identify columns with missing values
missing_info = final_features_df.isnull().sum()
missing_columns = missing_info[missing_info > 0].index.tolist()

print("Columns with missing values before imputation:", missing_columns)

# Decide on imputation strategy - using median for numerical columns and a constant for others if needed
# Based on previous steps, the new aggregated columns (total_claim_count, etc.) might have NaNs for beneficiaries
# who didn't have any claims. These should likely be imputed with 0.
# BENE_DEATH_DT has NaNs for living patients, which is expected and handled by readmission flags.

# Impute aggregated claims/drug/condition features with 0 for beneficiaries with no data
aggregated_cols = ['total_claim_count', 'total_reimbursement', 'total_beneficiary_deductible', 'average_length_of_stay',
                   'had_readmit_30', 'had_readmit_60', 'had_readmit_90', 'total_drug_exposures', 'total_days_supply',
                   'total_condition_occurrences']
for col in aggregated_cols:
    if col in final_features_df.columns:
        final_features_df[col] = final_features_df[col].fillna(0)

# Re-check missing values after imputing aggregated columns
missing_info_after_agg_impute = final_features_df.isnull().sum()
missing_columns_after_agg_impute = missing_info_after_agg_impute[missing_info_after_agg_impute > 0].index.tolist()

print("Columns with missing values after imputing aggregated features:", missing_columns_after_agg_impute)

# Handle other potential missing values if any remain in relevant columns
# For simplicity and based on previous analysis, we might not need complex imputation for other columns for this task,
# but if there were significant NaNs in key demographic/chronic condition columns, we would address them here.
# Example: If BENE_SEX_IDENT_CD had NaNs, we could impute with the mode.

# 3. Identify categorical columns for encoding
# BENE_SEX_IDENT_CD, BENE_RACE_CD, BENE_ESRD_IND, SP_STATE_CODE, BENE_COUNTY_CD, Chronic condition flags (SP_...)
categorical_cols = ['BENE_SEX_IDENT_CD', 'BENE_RACE_CD', 'BENE_ESRD_IND', 'SP_STATE_CODE', 'BENE_COUNTY_CD']
# Add chronic condition columns - these are already encoded as 1 or 2, we might treat them as categorical or numerical.
# Let's treat them as categorical for now, but map 2 to 0 to represent absence.
chronic_condition_cols = [col for col in final_features_df.columns if col.startswith('SP_') and col != 'SP_STATE_CODE']
for col in chronic_condition_cols:
    final_features_df[col] = final_features_df[col].replace(2, 0)
    categorical_cols.append(col)

# Ensure selected categorical columns exist
categorical_cols = [col for col in categorical_cols if col in final_features_df.columns]

print("Categorical columns identified for encoding:", categorical_cols)

# Separate numerical columns for potential different preprocessing
numerical_cols = final_features_df.select_dtypes(include=np.number).columns.tolist()
# Remove the target variables and identifier from numerical columns
target_cols = ['had_readmit_30', 'had_readmit_60', 'had_readmit_90']
numerical_cols = [col for col in numerical_cols if col not in target_cols + ['DESYNPUF_ID']]
# Remove the categorical columns from numerical columns list
numerical_cols = [col for col in numerical_cols if col not in categorical_cols]


# Create preprocessing pipelines for numerical and categorical features
# Numerical pipeline: Impute with median (although we already imputed aggregated features with 0)
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')) # Median might be better for other numerical features if they had NaNs
])

# Categorical pipeline: Impute with a constant (e.g., 'missing') and then one-hot encode
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ],
    remainder='passthrough' # Keep other columns (like DESYNPUF_ID and target variables)
)

# 5. Define the target variables
# Let's focus on predicting readmission within 30 days for this example
target_variable = 'had_readmit_30'

# 6. Separate features (X) and target variable (y)
X = final_features_df.drop(columns=target_cols + ['DESYNPUF_ID', 'BENE_BIRTH_DT', 'BENE_DEATH_DT']) # Drop identifier and date columns as well
y = final_features_df[target_variable]

# Apply the preprocessing steps to the features
X_processed = preprocessor.fit_transform(X)

# 7. Split data into training and testing sets
# Use stratification as readmission might be an imbalanced class
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42, stratify=y)

# 8. Verify the shapes of the resulting sets
print("\nShape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""**Reasoning**:
The error indicates that `final_features_df` is not defined. This is because the code cell that created it was not executed in the current session. I need to re-execute the code to create `final_features_df` before proceeding with data preparation.


"""